seed = 0
parent_dir = "exp/higgs-small/"
real_data_path = "data/higgs-small/"
model_type = "mlp"
num_numerical_features = 28
device = "cuda:1"

[preprocess]
contain_missing = false
block_size = 512
filter_threshold_param = 0.1
augment_threshold_param = 0.01
feature_dim = 100
pretrain_sample_num = 62751

[model_params]
d_in = 28
num_classes = 2
is_y_cond = true

[model_params.rtdl_params]
d_layers = [
    256,
    256,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 1000
gaussian_loss_type = "mse"
scheduler = "cosine"

[train.main]
steps = 100
lr = 0.08
weight_decay = 1e-05
batch_size = 1024

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[sample]
num_samples = 62751
batch_size = 6000
seed = 0

[eval.type]
eval_model = "mlp"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
